# Generated by Django 5.1.4 on 2025-01-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teammember_rename_services_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='heading',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='description',
        ),
        migrations.AddField(
            model_name='teammember',
            name='designation',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instgram_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_file',
            field=models.ImageField(upload_to='teams'),
        ),
    ]
