# Generated by Django 5.1.4 on 2025-01-13 09:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
